# Generated by Django 5.1.3 on 2024-12-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0003_alter_basket_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateTimeField(null=True),
        ),
    ]
